Origin/contacts
SeregaDS/demo_test pull request #19
Opened 2022-05-07 19:49 UTC by GDionis

BEM

2022-05-07 20:01 UTC, SeregaDS requested changes

2022-05-07 20:01 UTC, SeregaDS commented on src/partials/contacts.html
> +            <button class="btn__locations" type="button">
и дальше по бэму, слишком общий класс, могут быть конфликты в дальнейшем

2022-05-07 20:01 UTC, SeregaDS commented on src/sass/components/_contacts.scss
> +  &__title {
вытянуть классы в отдельные

2022-05-08 08:28 UTC, GDionis commented on src/partials/contacts.html
> +        <h1 class="contacts__title">Contacts</h1>
Исправлено

2022-05-08 08:28 UTC, GDionis commented on src/partials/contacts.html
> +                        <h3 class="contacts__days">Monday - Friday</h3>
Исправлено

2022-05-08 08:29 UTC, GDionis commented on src/partials/contacts.html
> +                        <a class="contacts__link" href="tel:+61(0)383766284 ">
Исправлено

2022-05-08 08:30 UTC, GDionis commented on src/partials/contacts.html
> +                        <h3 class="contacts__days">Saturday - Sunday</h3>
Исправлено

2022-05-08 08:30 UTC, GDionis commented on src/partials/contacts.html
> +                        <h3 class="contacts__days">Saturday - Sunday</h3>
Исправлено

2022-05-08 08:30 UTC, GDionis commented on src/partials/contacts.html
> +                        <h3 class="contacts__days">Saturday - Sunday</h3>
Исправлено

2022-05-08 08:30 UTC, GDionis commented on src/partials/contacts.html
> +                        <a class="contacts__link" href="tel:+61(0)383766284 ">
Исправлено

2022-05-08 08:32 UTC, GDionis commented on src/partials/contacts.html
> +        <div class="btn">
Исправлено

2022-05-08 08:43 UTC, GDionis commented on src/partials/contacts.html
> +            <button class="btn__locations" type="button">
Исправлено

2022-05-08 08:45 UTC, GDionis commented on src/sass/components/_contacts.scss
> +  &__title {
Исправлено

2022-05-08 08:52 UTC, SeregaDS approved these changes

2022-05-08 08:52 UTC, merged